import os
from pathlib import Path

import ttkbootstrap as ttk
from ttkbootstrap.constants import *
from tkinter import messagebox


class ReportsPage:

    def __init__(self, parent, app):

        self.app = app

        self.frame = ttk.Frame(parent)
        self.frame.pack(fill="both", expand=True)

        # =========================
        # HEADER
        # =========================

        ttk.Label(
            self.frame,
            text="📑 Reports",
            font=("Segoe UI", 28, "bold"),
            bootstyle="primary"
        ).pack(pady=(20, 5))

        ttk.Label(
            self.frame,
            text="View and manage files generated by Excel Automation Toolkit.",
            font=("Segoe UI", 12)
        ).pack(pady=(0, 25))

        # =========================
        # OUTPUT FOLDER
        # =========================

        folder_frame = ttk.Frame(self.frame)
        folder_frame.pack(fill="x", padx=40, pady=10)

        ttk.Label(
            folder_frame,
            text="Output Folder:",
            font=("Segoe UI", 11, "bold")
        ).pack(side=LEFT)

        self.folder_label = ttk.Label(
            folder_frame,
            text=self.get_output_folder(),
            font=("Segoe UI", 10),
            bootstyle="secondary"
        )

        self.folder_label.pack(
            side=LEFT,
            padx=10
        )

        ttk.Button(
            folder_frame,
            text="📂 Open Folder",
            command=self.open_output_folder,
            bootstyle="info"
        ).pack(side=RIGHT)

        # =========================
        # SEPARATOR
        # =========================

        ttk.Separator(
            self.frame,
            orient="horizontal"
        ).pack(
            fill="x",
            padx=40,
            pady=20
        )

        # =========================
        # REPORT TITLE
        # =========================

        ttk.Label(
            self.frame,
            text="Generated Files",
            font=("Segoe UI", 18, "bold")
        ).pack(
            anchor="w",
            padx=40,
            pady=(0, 15)
        )

        # =========================
        # FILES FRAME
        # =========================

        self.files_frame = ttk.Frame(self.frame)
        self.files_frame.pack(
            fill="both",
            expand=True,
            padx=40
        )

        # =========================
        # REFRESH BUTTON
        # =========================

        ttk.Button(
            self.frame,
            text="🔄 Refresh Reports",
            command=self.refresh_reports,
            bootstyle="primary",
            width=25
        ).pack(
            pady=20
        )

        # Load files
        self.refresh_reports()

    # =====================================================
    # GET OUTPUT FOLDER
    # =====================================================

    def get_output_folder(self):

        folder = self.app.settings.get(
            "output_folder",
            ""
        )

        if folder:
            return folder

        return "Output folder not configured"

    # =====================================================
    # REFRESH REPORTS
    # =====================================================

    def refresh_reports(self):

        # Remove old widgets
        for widget in self.files_frame.winfo_children():
            widget.destroy()

        output_folder = self.app.settings.get(
            "output_folder",
            ""
        )

        if not output_folder:

            ttk.Label(
                self.files_frame,
                text="⚠ No output folder configured.",
                font=("Segoe UI", 12),
                bootstyle="warning"
            ).pack(pady=30)

            return

        output_path = Path(output_folder)

        if not output_path.exists():

            ttk.Label(
                self.files_frame,
                text="📂 Output folder does not exist yet.",
                font=("Segoe UI", 12),
                bootstyle="warning"
            ).pack(pady=30)

            return

        files = list(output_path.iterdir())

        if not files:

            ttk.Label(
                self.files_frame,
                text="📭 No generated files found.",
                font=("Segoe UI", 12),
                bootstyle="secondary"
            ).pack(pady=30)

            return

        # =========================
        # FILE HEADER
        # =========================

        header = ttk.Frame(self.files_frame)
        header.pack(
            fill="x",
            pady=(0, 5)
        )

        ttk.Label(
            header,
            text="File Name",
            font=("Segoe UI", 10, "bold")
        ).pack(
            side=LEFT,
            padx=10
        )

        ttk.Label(
            header,
            text="Size",
            font=("Segoe UI", 10, "bold")
        ).pack(
            side=RIGHT,
            padx=150
        )

        ttk.Label(
            header,
            text="Action",
            font=("Segoe UI", 10, "bold")
        ).pack(
            side=RIGHT,
            padx=20
        )

        ttk.Separator(
            self.files_frame,
            orient="horizontal"
        ).pack(
            fill="x",
            pady=5
        )

        # =========================
        # FILE LIST
        # =========================

        for file in sorted(files):

            if not file.is_file():
                continue

            self.create_file_row(file)

    # =====================================================
    # CREATE FILE ROW
    # =====================================================

    def create_file_row(self, file):

        row = ttk.Frame(self.files_frame)

        row.pack(
            fill="x",
            pady=6
        )

        # File icon
        extension = file.suffix.lower()

        icons = {
            ".xlsx": "📗",
            ".csv": "📄",
            ".pdf": "📕",
            ".zip": "📦"
        }

        icon = icons.get(
            extension,
            "📄"
        )

        # File name

        ttk.Label(
            row,
            text=f"{icon} {file.name}",
            font=("Segoe UI", 11)
        ).pack(
            side=LEFT,
            padx=10
        )

        # Size

        size = self.get_file_size(file)

        ttk.Label(
            row,
            text=size,
            font=("Segoe UI", 10)
        ).pack(
            side=RIGHT,
            padx=150
        )

        # Open button

        ttk.Button(
            row,
            text="Open",
            command=lambda f=file: self.open_file(f),
            bootstyle="success-outline",
            width=10
        ).pack(
            side=RIGHT,
            padx=20
        )

        ttk.Separator(
            self.files_frame,
            orient="horizontal"
        ).pack(
            fill="x",
            pady=3
        )

    # =====================================================
    # FILE SIZE
    # =====================================================

    def get_file_size(self, file):

        try:

            size = file.stat().st_size

            if size < 1024:
                return f"{size} B"

            if size < 1024 * 1024:
                return f"{size / 1024:.1f} KB"

            return f"{size / (1024 * 1024):.1f} MB"

        except Exception:
            return "Unknown"

    # =====================================================
    # OPEN FILE
    # =====================================================

    def open_file(self, file):

        try:

            if not file.exists():

                messagebox.showerror(
                    "File Not Found",
                    f"File does not exist:\n\n{file}"
                )

                return

            os.startfile(file)

        except Exception as e:

            messagebox.showerror(
                "Error",
                f"Unable to open file.\n\n{e}"
            )

    # =====================================================
    # OPEN OUTPUT FOLDER
    # =====================================================

    def open_output_folder(self):

        folder = self.app.settings.get(
            "output_folder",
            ""
        )

        if not folder:

            messagebox.showwarning(
                "Output Folder",
                "Please configure the output folder in Settings first."
            )

            return

        folder_path = Path(folder)

        if not folder_path.exists():

            messagebox.showerror(
                "Folder Not Found",
                f"The output folder does not exist:\n\n{folder}"
            )

            return

        try:

            os.startfile(folder_path)

        except Exception as e:

            messagebox.showerror(
                "Error",
                f"Unable to open output folder.\n\n{e}"
            )